version: "3"

services:
    web1:
        restart: always
        build: ./server
        container_name: web1
        ports:
            - "81:80"

    web2:
        restart: always
        build: ./server
        container_name: web2
        ports:
            - "82:80"

    haproxy:
        build: ./haproxy
        container_name: haproxy
        ports:
            - "80:80"